### ISSUE TITLE
Sill Having IOError: [Errno 11]

### ISSUE THREAD

**Issue by coderant** [Janhouse/tespeed#29] opened 2014-08-11 11:28 UTC
```
89 ms latency for http://speedtest.nyc.public.inerail.net/speedtest/ (Inerail, New York City, NY, United States) [1.00 km]
Traceback (most recent call last):
  File "./tespeed/tespeed.py", line 665, in <module>
    main(args)
  File "./tespeed/tespeed.py", line 640, in main
    chunksize=args.chunksize
  File "./tespeed/tespeed.py", line 148, in __init__
    self.TestSpeed()
  File "./tespeed/tespeed.py", line 590, in TestSpeed
    self.TestDownload()
  File "./tespeed/tespeed.py", line 556, in TestDownload
    sizes, took=self.AsyncRequest(url, thrds )
  File "./tespeed/tespeed.py", line 430, in AsyncRequest
    d=Manager().dict()
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 634, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 532, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.6/multiprocessing/connection.py", line 149, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.6/multiprocessing/connection.py", line 383, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable
```
Any fix for now?

**Comment by Janhouse** [comment] 2015-07-26 21:23
Duplicate of #22

**Closed by Janhouse** 2015-07-26 21:23 UTC
